### ISSUE TITLE
System kind is missing codeLocations under datadog

### ISSUE THREAD

**Issue by mattm-ecoatm** [DataDog/schema#76]
The example shows it should be possible:

https://docs.datadoghq.com/software_catalog/service_definitions/v3-0/#example-yaml-for-kindsystem

```
datadog:
  codeLocations:
    - repositoryURL: https://github.com/myorganization/myrepo.git
      paths:
        - path/to/service/code/**
```

The UI shows a link type in a system kind as well. But this is missing from the schema.

https://github.com/DataDog/schema/blob/9118fa944e7a0cf5a570a2de1a898b45ef8b9470/service-catalog/v3/system.schema.json#L80-L89

Service allows it as defined here https://github.com/DataDog/schema/blob/9118fa944e7a0cf5a570a2de1a898b45ef8b9470/service-catalog/v3/service.schema.json#L129-L130
